# Generated by Django 3.2.7 on 2021-09-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.URLField(default='https://picsum.photos/seed/picsum/200'),
        ),
    ]
